[project]
name = "system-retrieval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.2",
    "scikit-learn>=1.7.2",
    "whoosh>=2.7.4",
]
